Repository swcarpentry/r-novice-gapminder, pull requests merged in 2018-04, with the labels that each got.

#372 remove out of date comment in 07-control-flow.Rmd
  _episodes_rmd/07-control-flow.Rmd
Labels: status:completed, type:typo-text

#375 Update style to v9.4.0
  CONDUCT.md
  _extras/figures.md
  _includes/lc/intro.html
  _includes/lc/syllabus.html
  _includes/lesson_footer.html
  _includes/links.md
  _includes/navbar.html
  _includes/workshop_footer.html
  _layouts/base.html
  assets/css/bootstrap.css
  assets/css/lesson.scss
  assets/img/swc-icon-blue.svg
  assets/img/swc-logo-blue.svg
  assets/img/swc-logo-white.svg
  bin/generate_md_episodes.R
  bin/lesson_initialize.py
  bin/repo_check.py
Labels: status:pr-in-review

#377 Improve link text for screen readers
  _episodes_rmd/02-project-intro.Rmd
  _episodes_rmd/15-knitr-markdown.Rmd
Labels: type:enhancement
