Repository swcarpentry/r-novice-gapminder, pull requests merged in 2018-03, with the labels that each got.

#358 fix one erratum
  _episodes_rmd/05-data-structures-part2.Rmd
Labels: status:pr-in-review, type:clarification

#316 formatting a list of things as a list
  _episodes_rmd/01-rstudio-intro.Rmd
Labels: status:help-wanted, type:formatting

#360 Wording edits
  _episodes_rmd/05-data-structures-part2.Rmd
Labels: status:pr-in-review, type:clarification

#362 Add section demonstrating how to remove columns from a df
  _episodes_rmd/05-data-structures-part2.Rmd
Labels: status:pr-in-review, type:enhancement
