Repository swcarpentry/r-novice-gapminder, pull requests merged in 2019-11, with the labels that each got.

#584 - issue #580: don't repeat the challenge text
  _episodes_rmd/08-plot-ggplot2.Rmd
Labels: status:changes requested, type:clarification

#566 Added tip on R's build-in ifelse() function!
  _episodes_rmd/07-control-flow.Rmd
Labels: status:changes requested, type:enhancement

#588 challange 5 - boxplot
  _episodes_rmd/08-plot-ggplot2.Rmd
Labels: type:enhancement
