Repository swcarpentry/r-novice-gapminder, pull requests merged in 2023-04, with the labels that each got.

#765 Create 15-knitr-markdown.Rmd
  _episodes_rmd/15-knitr-markdown.Rmd
Labels: status:changes requested, type:clarification

#737 Lession 4: Remove factors, simpler lists, dedicated names, separate typeof and class, data cleanup challenge.
  _episodes_rmd/04-data-structures-part1.Rmd
Labels: type:enhancement

#824 Update to final version of styles lesson template
  .github/PULL_REQUEST_TEMPLATE.md
  LICENSE.md
  _includes/check_transition_variables.html
  _includes/javascript.html
  _includes/lesson_footer.html
  _includes/life_cycle.html
  _includes/manual_episode_order.html
  _includes/navbar.html
  _layouts/base.html
  aio.md
  assets/css/lesson.scss
  bin/boilerplate/.travis.yml
  bin/boilerplate/_config.yml
  bin/lesson_initialize.py
Labels: type:template and tools
